Adding Unit Test steps to the CI workflow

diff --git a/.github/workflows/reusable-ci.yml b/.github/workflows/reusable-ci.yml
--- a/.github/workflows/reusable-ci.yml
+++ b/.github/workflows/reusable-ci.yml
@@ -34,8 +34,32 @@ jobs:
       - name: Build and Test (Reactor)
         run: mvn clean install -pl ${{ inputs.service-name }} -am -DskipTests
 
-#      - name: Run Unit Tests
-#        run: mvn test
+      # --fail-at-end ensures target/surefire-reports are generated even if tests fail
+      - name: Build and Run Tests
+        run: mvn test --batch-mode --fail-at-end
+
+      # This runs whether the previous test step succeeded or failed
+      - name: Publish Surefire Test Report
+        if: success() || failure()
+        uses: ScalableCapital/action-surefire-report@v2
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+################### Disabling Integration TESTS  FOR NOW .......!!!!!
+#      # Use 'verify' instead of 'test' to trigger the Failsafe plugin
+#      - name: Build and Run All Tests
+#        run: mvn clean verify --batch-mode
+#
+#      # Publish both Surefire (Unit) and Failsafe (Integration) results
+#      - name: Publish Test Report
+#        if: success() || failure()
+#        uses: ScalableCapital/action-surefire-report@v2
+#        with:
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          # Tells the action to look for both sets of XML reports
+#          report_paths: |
+#            **/target/surefire-reports/TEST-*.xml
+#            **/target/failsafe-reports/TEST-*.xml
 
       - name: Login to Container Registry
         uses: docker/login-action@v4
@@ -43,8 +67,6 @@ jobs:
           registry: ${{ env.DOCKER_REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-#          username: ${{ secrets.DOCKER_USERNAME }}
-#          password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v6
